services:
  postgres_main:
    container_name: calc_database_main
    image: postgres:17
    restart: unless-stopped
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
        # ports:
        # - "5433:5432"
    expose:
      - "5432"

  backend:
    container_name: calc_backend
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    entrypoint: "/entrypoint.sh"
    command: > 
      /bin/sh -c "
      echo \"Starting gunicorn with $workers workers\";
      uv run gunicorn config.wsgi:application
      --bind 0.0.0.0:8002
      --threads 2
      --timeout 120
      --keep-alive 5
      --access-logfile -
      --error-logfile -
      --capture-output
      --log-level info
      "
    restart: unless-stopped
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
    env_file:
      - .env.prod
    depends_on:
      - postgres_main
    ports:
      - "8002:8002"

  nginx:
    container_name: calc_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/config/calc.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/static:ro
      - media_data:/media:ro
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  pg_data:
  static_data:
  media_data:
